package:
  name: hdf5-parallel
  version: "1.8.19"

source:
   fn: hdf5-1.8.19.tar.gz
   url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.19/src/hdf5-1.8.19.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - mpich
  run:
    - mpich


about:
  home: https://www.hdfgroup.org/
  license: BSD
  license_file: COPYING
  summary: Parallel HDF5 library
