package:
  name: hdf5-parallel
  version: 1.8.19

source:
   path: /Users/etotoni/Downloads/hdf5-1.8.19

build:
  number: 0
  script_env:
    - CC
    - CXX

requirements:
  build:
    - gcc
    - mpich
  run:
    - gcc
    - mpich


about:
  home: https://www.hdfgroup.org/
  license: BSD
  license_file: COPYING
  summary: Parallel HDF5 library
