version: '3'

networks:
  mynet:
    driver: overlay

services:
    mpi_node1:
        # image: hpatv0.1:latest
        build: .
        ports:
          - "22"
        networks:
          - mynet

    mpi_node2:
        build: .
        ports:
          - "22"
        # image: hpatv0.1:latest
        networks:
          - mynet

    mpi_node3:
        build: .
        ports:
          - "22"
        # image: hpatv0.1:latest
        networks:
          - mynet

    mpi_node4:
        build: .
        ports:
          - "22"
        # image: hpatv0.1:latest
        networks:
          - mynet
