package:
  name: hpat
  version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python 3.6.*
    - setuptools
    - numpy 1.13.*
    - pandas
    - scipy
    - mpich
    - pyarrow
    - numba
    - hdf5-parallel
    - h5py

  run:
    - python
    - numpy
    - pandas
    - scipy
    - mpich
    - pyarrow
    - numba
    - hdf5-parallel
    - h5py

test:
  imports:
    - hpat


about:
  home: https://github.com/IntelLabs/hpat
  license: BSD
  license_file: LICENSE.md
  summary: A compiler-based big data framework in Python
